import { ArrowUpRight, BarChart3, ExternalLink, Radio, Sparkles, UserRound } from 'lucide-react'
import { SiGithub, SiGmail } from 'react-icons/si'
import { FaLinkedin } from 'react-icons/fa'

const scrollButton = (scrollTo) => <button className="text-link" onClick={() => scrollTo('contact')}>More about my approach <ArrowUpRight size={16} /></button>

export function Trusted() { return <section className="trusted section-pad"><p className="section-kicker">WORKING ACROSS THE DATA STACK</p><div className="logos"><span>REACT</span><span>RED<span className="dot">SHIFT</span></span><span className="logo-serif">Snow<span>flake</span></span><span>DBT<span className="dot">.</span></span><span>AWS</span></div></section> }

export function Work() { return <section className="work section-pad" id="work"><div className="section-heading"><div><p className="section-kicker">SELECTED SYSTEMS / 2021—24</p><h2>Work that holds<br /><em>under pressure.</em></h2></div><p className="section-note">Production platforms, dashboards,<br />and data-informed interfaces.</p></div><div className="project-grid"><article className="project project-dark"><ProjectTop label="01 / FINANCIAL PLATFORM" sector="KFIN" /><div className="pipeline-art"><div className="data-node node-a">API</div><div className="data-node node-b">LAMF</div><div className="data-node node-c">TRACK</div><div className="connector c-one" /><div className="connector c-two" /><div className="chart-line"><i /><i /><i /><i /><i /><i /></div></div><ProjectInfo title="LAMF" accent="Platform" text="Secure Loan Against Mutual Fund workflows with real-time transaction tracking." tags={['React', 'REST APIs', 'Chart.js']} /></article><article className="project project-lime"><ProjectTop label="02 / DATA WORKFLOWS" sector="EXAVALU" /><div className="signal-art"><BarChart3 size={30} /><div className="bars"><i /><i /><i /><i /><i /><i /><i /></div><span className="signal-label">25%</span></div><ProjectInfo title="Data" accent="Signals" text="Analytics-ready dashboards and performant interfaces for investor and corporate workflows." tags={['Redux', 'Tailwind', 'SQL']} /></article></div></section> }
function ProjectTop({ label, sector }) { return <div className="project-top"><span>{label}</span><span>{sector}</span></div> }
function ProjectInfo({ title, accent, text, tags }) { return <div className="project-info"><h3>{title} <em>{accent}</em></h3><p>{text}</p><div className="tags">{tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div> }

export function About({ scrollTo }) { return <section className="statement section-pad" id="about"><div className="statement-mark"><Sparkles size={22} /></div><p className="section-kicker">THE HUMAN LAYER</p><h2>Good infrastructure is<br /><em>felt, not seen.</em></h2><p className="statement-copy">I care about the invisible things: a pipeline that doesn’t wake you up, a metric everyone trusts, and a team that knows exactly where to look next.</p>{scrollButton(scrollTo)}</section> }

export function Stack() { return <section className="stack section-pad" id="stack"><div className="section-heading"><div><p className="section-kicker">THE TOOLKIT</p><h2>Tools for the<br /><em>long haul.</em></h2></div><div className="live-status"><span className="pulse" /> CURRENTLY LEARNING <strong>Data engineering</strong></div></div><div className="stack-list"><StackRow number="01" title="Frontend & state" tools="React / Redux Toolkit / TypeScript" /><StackRow number="02" title="Cloud & warehousing" tools="AWS S3 / Redshift / Snowflake" /><StackRow number="03" title="Transformation & data" tools="dbt / SQL / MySQL / SQL Server" /><StackRow number="04" title="Testing & delivery" tools="Jest / RTL / Git / Agile" /></div></section> }
function StackRow({ number, title, tools }) { return <div><span>{number}</span><strong>{title}</strong><p>{tools}</p></div> }

export function Contact() { return <section className="contact section-pad" id="contact"><div className="contact-inner"><Radio size={19} /><p className="section-kicker">HAVE A SIGNAL?</p><h2>Let’s build what’s<br /><em>next.</em></h2><a className="email-link" href="mailto:deepdubey1995@gmail.com" target="_blank" rel="noreferrer">deepdubey1995@gmail.com <ArrowUpRight size={19} /></a><div className="contact-details"><a href="tel:+919052057751">+91 90520 57751</a><a href="tel:+919133901574">+91 91339 01574</a></div></div></section> }
export function Footer() { return <footer><span>© 2024 DEEP DUBEY</span><span>ENGINEERED WITH INTENT</span><div className="social-links"><a href="mailto:deepdubey1995@gmail.com" target="_blank" rel="noreferrer" aria-label="Email Deep Dubey"><SiGmail size={17} /></a><a href="https://www.linkedin.com/in/deep-dubey-140650a6/" target="_blank" rel="noreferrer" aria-label="Deep Dubey on LinkedIn"><FaLinkedin size={17} /></a><a href="https://github.com/Deep-Dubey" target="_blank" rel="noreferrer" aria-label="Deep Dubey on GitHub"><SiGithub size={17} /></a><a href="#home" aria-label="Profile"><UserRound size={17} /></a><ExternalLink size={13} className="footer-external" /></div></footer> }
