import { ArrowUpRight, BarChart3, ExternalLink, Radio, Sparkles, UserRound } from 'lucide-react'
import { SiGithub, SiGmail } from 'react-icons/si'
import { FaLinkedin } from 'react-icons/fa'

const scrollButton = (scrollTo) => <button className="text-link" onClick={() => scrollTo('contact')}>Get in touch <ArrowUpRight size={16} /></button>

export function Trusted() { return <section className="trusted section-pad"><p className="section-kicker">WORKING ACROSS THE DATA STACK</p><div className="logos"><span>Azure</span><span>Snowflake</span><span className="logo-serif">DBT</span><span>Python</span><span>SQL</span><span>Kafka</span><span>Airflow</span><span>Databricks</span><span>BigQuery</span></div></section> }

export function Work() { return <section className="work section-pad" id="work"><div className="section-heading"><div><p className="section-kicker">PROJECTS / GITHUB</p><div className="project-header-wrap"><h2>Work that holds<br /><em>under pressure.</em></h2><a className="profile-link" href="https://github.com/Deep-Dubey" target="_blank" rel="noreferrer">GitHub profile <ArrowUpRight size={14} /></a></div></div><p className="section-note">Production-style pipelines, validation logic, and analytics-ready data products.</p></div><div className="project-grid"><article className="project project-dark"><ProjectTop label="01 / FINANCIAL TRADE PROCESSING PLATFORM" sector="GCP" /><div className="pipeline-art"><div className="data-node node-a">GCS</div><div className="data-node node-b">PySpark</div><div className="data-node node-c">BigQuery</div><div className="connector c-one" /><div className="connector c-two" /><div className="chart-line"><i /><i /><i /><i /><i /><i /></div></div><ProjectInfo title="Trade" accent="Validation" text="Built a production-style financial trade platform on GCP using PySpark, implementing 10+ business validation rules and automated reject handling with audit reporting." tags={['PySpark', 'BigQuery', 'Airflow', 'Terraform']} link="https://github.com/Deep-Dubey/financial-trade-platform" /></article><article className="project project-lime"><ProjectTop label="02 / ENTERPRISE SALES ETL PIPELINE" sector="GCP" /><div className="signal-art"><BarChart3 size={30} /><div className="bars"><i /><i /><i /><i /><i /><i /><i /></div><span className="signal-label">ETL</span></div><ProjectInfo title="Sales" accent="Pipeline" text="Built an enterprise-grade sales ETL pipeline orchestrated with Airflow and executed on Dataproc clusters, with event-driven automation using Cloud Functions." tags={['PySpark', 'Dataproc', 'Cloud Functions', 'GitHub Actions']} link="https://github.com/Deep-Dubey/enterprise-sales-etl" /></article><article className="project project-dark"><ProjectTop label="03 / BANKING REAL-TIME DATA PLATFORM" sector="KAFKA" /><div className="pipeline-art"><div className="data-node node-a">Kafka</div><div className="data-node node-b">Schema</div><div className="data-node node-c">GCS</div><div className="connector c-one" /><div className="connector c-two" /><div className="chart-line"><i /><i /><i /><i /><i /><i /></div></div><ProjectInfo title="Realtime" accent="Banking" text="Built a real-time banking data platform using Apache Kafka and Schema Registry to stream simulated transaction events into Google Cloud Storage for downstream processing." tags={['Kafka', 'Airflow', 'GCS', 'Streaming']} link="https://github.com/Deep-Dubey/banking-realtime-platform/tree/main/banking-realtime-platform" /></article></div></section> }
function ProjectTop({ label, sector }) { return <div className="project-top"><span>{label}</span><span>{sector}</span></div> }
function ProjectInfo({ title, accent, text, tags, link }) { return <div className="project-info"><h3>{title} <em>{accent}</em></h3><p>{text}</p><div className="tags">{tags.map((tag) => <span key={tag}>{tag}</span>)}</div>{link ? <a className="project-link" href={link} target="_blank" rel="noreferrer">View project <ArrowUpRight size={14} /></a> : null}</div> }

export function About({ scrollTo }) { return <section className="statement section-pad" id="about"><div className="statement-mark"><Sparkles size={22} /></div><p className="section-kicker">PROFESSIONAL SUMMARY</p><h2>Building resilient data systems<br /><em>for finance and growth.</em></h2><p className="statement-copy">Software Engineer with 4+ years of experience building secure, compliant, and scalable data pipelines for the financial services and fintech domain, including lending, investment, and portfolio management platforms. Strong expertise in Azure, Snowflake, SQL, Python, DBT, and data validation with a focus on audit readiness, performance optimization, and trusted reporting.</p>{scrollButton(scrollTo)}<div style={{ marginTop: '1.25rem', display: 'grid', gap: '0.55rem', color: 'var(--muted)' }}><strong style={{ color: 'var(--paper)', fontWeight: 500 }}>Soft Skills & Collaboration</strong><span>• Strong communication and stakeholder presentation skills</span><span>• Skilled in code and pipeline reviews with mentoring junior engineers</span><span>• Analytical mindset focused on performance, cost optimization, and data quality</span></div></section> }

export function Stack() { return <section className="stack section-pad" id="stack"><div className="section-heading"><div><p className="section-kicker">THE TOOLKIT</p><h2>Tools for the<br /><em>data domain.</em></h2></div><div className="live-status"><span className="pulse" /> CURRENTLY WORKING <strong>on data engineering, production analytics & pipelines</strong></div></div><div className="stack-list"><StackRow number="01" title="Cloud platforms" tools="Microsoft Azure / Google Cloud Platform" /><StackRow number="02" title="Data warehousing" tools="Snowflake / Azure Synapse Analytics / BigQuery" /><StackRow number="03" title="Big data & streaming" tools="PySpark / Kafka / Schema Registry / Dataproc" /><StackRow number="04" title="Transformation & orchestration" tools="DBT / ADF / Airflow / Cloud Composer / SSIS" /><StackRow number="05" title="Data modeling & processing" tools="SQL / Python / Data Cleansing / Data Validation / ETL/ELT" /><StackRow number="06" title="Infrastructure & delivery" tools="Docker / GitHub Actions / CI/CD / Git / OIDC auth" /></div></section> }
function StackRow({ number, title, tools }) { return <div><span>{number}</span><strong>{title}</strong><p>{tools}</p></div> }

export function Contact() { return <section className="contact section-pad" id="contact"><div className="contact-inner"><Radio size={19} /><p className="section-kicker">HAVE A SIGNAL?</p><h2>Let’s build what’s<br /><em>next.</em></h2><a className="email-link" href="mailto:deepdubey1995@gmail.com" target="_blank" rel="noreferrer">deepdubey1995@gmail.com <ArrowUpRight size={19} /></a><div className="contact-details"><a href="https://www.linkedin.com/in/deep-dubey-140650a6/" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://github.com/Deep-Dubey" target="_blank" rel="noreferrer">GitHub</a><a href="tel:+919052057751">+91 90520 57751</a><a href="https://maps.google.com/?q=Hyderabad,India" target="_blank" rel="noreferrer">Hyderabad, India</a></div></div></section> }
export function Footer() { return <footer><span>© 2024 DEEP DUBEY</span><span>SOFTWARE ENGINEER</span><div className="social-links"><a href="mailto:deepdubey1995@gmail.com" target="_blank" rel="noreferrer" aria-label="Email Deep Dubey"><SiGmail size={17} /></a><a href="https://www.linkedin.com/in/deep-dubey-140650a6/" target="_blank" rel="noreferrer" aria-label="Deep Dubey on LinkedIn"><FaLinkedin size={17} /></a><a href="https://github.com/Deep-Dubey" target="_blank" rel="noreferrer" aria-label="Deep Dubey on GitHub"><SiGithub size={17} /></a><a href="https://github.com/Deep-Dubey" target="_blank" rel="noreferrer" aria-label="Deep Dubey GitHub Profile"><UserRound size={17} /></a><a href="/Deep_Dubey.pdf" download="Deep_Dubey_Resume.pdf" aria-label="Download Deep Dubey resume"><ExternalLink size={13} className="footer-external" /></a></div></footer> }
